[package]
name = "gazetta"
version = "0.1.0"
authors = ["Steven Allen <steven@stebalien.com>"]
description = """
A static site generator framework.

If you want to use or extend gazetta, see the gazetta-bin crate.
"""
documentation = "https://stebalien.github.io/gazetta/gazetta/"
repository = "https://github.com/Stebalien/gazetta"
keywords = ["staticsite", "website", "blog"]
license = "GPL-3.0"

[dependencies.gazetta-core]
path = "core"

[dependencies.gazetta-render-ext]
path = "render-ext"

[dependencies.gazetta-model-ext]
path = "model-ext"

[dependencies.gazetta-cli]
path = "cli"
