[package]
name = "gazetta"
version = "0.1.0"
authors = ["Steven Allen <steven@stebalien.com>"]

[dependencies.gazetta-core]
path = "core"

[dependencies.gazetta-render-ext]
path = "render-ext"

[dependencies.gazetta-model-ext]
path = "model-ext"

[dependencies.gazetta-cli]
path = "cli"
