[package]
name = "gazetta"
version = "0.1.0"
authors = ["Steven Allen <steven@stebalien.com>"]

[dependencies]
chrono = "*"
glob = "*"
yaml-rust = "*"
lazy_static = "*"
pulldown-cmark = "*"
horrorshow = "*"
url = "*"
