(function() {var implementors = {};
implementors["gazetta_render_ext"] = ["impl&lt;'a&gt; <a class=\"trait\" href=\"horrorshow/render/trait.Render.html\" title=\"trait horrorshow::render::Render\">Render</a> for <a class=\"struct\" href=\"gazetta_render_ext/struct.Markdown.html\" title=\"struct gazetta_render_ext::Markdown\">Markdown</a>&lt;'a&gt;","impl&lt;'a, G&gt; <a class=\"trait\" href=\"horrorshow/render/trait.Render.html\" title=\"trait horrorshow::render::Render\">Render</a> for <a class=\"struct\" href=\"gazetta_render_ext/struct.Assets.html\" title=\"struct gazetta_render_ext::Assets\">Assets</a>&lt;'a, G&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;G: <a class=\"trait\" href=\"gazetta_core/render/trait.Gazetta.html\" title=\"trait gazetta_core::render::Gazetta\">Gazetta</a> + 'a,<br>&nbsp;&nbsp;&nbsp;&nbsp;G::<a class=\"type\" href=\"gazetta_core/render/trait.Gazetta.html#associatedtype.SiteMeta\" title=\"type gazetta_core::render::Gazetta::SiteMeta\">SiteMeta</a>: 'a,<br>&nbsp;&nbsp;&nbsp;&nbsp;G::<a class=\"type\" href=\"gazetta_core/render/trait.Gazetta.html#associatedtype.PageMeta\" title=\"type gazetta_core::render::Gazetta::PageMeta\">PageMeta</a>: 'a,&nbsp;</span>","impl&lt;'a&gt; <a class=\"trait\" href=\"horrorshow/render/trait.Render.html\" title=\"trait horrorshow::render::Render\">Render</a> for <a class=\"struct\" href=\"gazetta_render_ext/struct.Date.html\" title=\"struct gazetta_render_ext::Date\">Date</a>&lt;'a&gt;","impl&lt;'a, G&gt; <a class=\"trait\" href=\"horrorshow/render/trait.Render.html\" title=\"trait horrorshow::render::Render\">Render</a> for <a class=\"struct\" href=\"gazetta_render_ext/struct.Content.html\" title=\"struct gazetta_render_ext::Content\">Content</a>&lt;'a, G&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;G: <a class=\"trait\" href=\"gazetta_core/render/trait.Gazetta.html\" title=\"trait gazetta_core::render::Gazetta\">Gazetta</a> + 'a,<br>&nbsp;&nbsp;&nbsp;&nbsp;G::<a class=\"type\" href=\"gazetta_core/render/trait.Gazetta.html#associatedtype.SiteMeta\" title=\"type gazetta_core::render::Gazetta::SiteMeta\">SiteMeta</a>: 'a,<br>&nbsp;&nbsp;&nbsp;&nbsp;G::<a class=\"type\" href=\"gazetta_core/render/trait.Gazetta.html#associatedtype.PageMeta\" title=\"type gazetta_core::render::Gazetta::PageMeta\">PageMeta</a>: 'a,&nbsp;</span>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
