[package]
name = "gazetta-cli"
version = "0.1.0"
authors = ["Steven Allen <steven@stebalien.com>"]

[dependencies.gazetta-core]
path = "../core"

[dependencies]
slug = "0.1"
lazy_static = "0.1"
chrono = "0.2"
clap = "1"
horrorshow = "0.5"
