[package]
name = "gazetta-cli"
version = "0.1.0"
authors = ["Steven Allen <steven@stebalien.com>"]
description = "A static site generator framework. Shared CLI code."
documentation = "https://stebalien.github.io/gazetta/gazetta_cli/"
repository = "https://github.com/Stebalien/gazetta"
keywords = ["staticsite", "website", "blog"]
license = "GPL-3.0"

[dependencies.gazetta-core]
path = "../core"

[dependencies]
slug = "0.1"
lazy_static = "0.1"
chrono = "0.2"
clap = "1"
horrorshow = "0.5"
