[package]
name = "gazetta-core"
version = "0.1.2"
authors = ["Steven Allen <steven@stebalien.com>"]
description = "A static site generator framework. Core."
documentation = "https://stebalien.github.io/gazetta/gazetta_core/"
homepage = "http://stebalien.com/projects/gazetta"
repository = "https://github.com/Stebalien/gazetta"
keywords = ["staticsite", "website", "blog"]
license = "GPL-3.0"

[dependencies]
chrono = "0.2"
glob = "0.2"
yaml-rust = "0.2"
lazy_static = "0.2"
horrorshow = "0.5"
url = "0.2"
str_stack = "0.1"
