(function() {var implementors = {};
implementors["horrorshow"] = ["impl&lt;S&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Deref.html' title='core::ops::Deref'>Deref</a> for <a class='struct' href='horrorshow/struct.Raw.html' title='horrorshow::Raw'>Raw</a>&lt;S&gt; <span class='where'>where S: <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html' title='core::convert::AsRef'>AsRef</a>&lt;<a class='primitive' href='https://doc.rust-lang.org/nightly/std/primitive.str.html'>str</a>&gt;</span>",];implementors["libc"] = [];implementors["ansi_term"] = ["impl&lt;'a,&nbsp;S:&nbsp;'a + <a class='trait' href='https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html' title='collections::borrow::ToOwned'>ToOwned</a> + ?<a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Sized.html' title='core::marker::Sized'>Sized</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Deref.html' title='core::ops::Deref'>Deref</a> for <a class='struct' href='ansi_term/struct.ANSIGenericString.html' title='ansi_term::ANSIGenericString'>ANSIGenericString</a>&lt;'a,&nbsp;S&gt; <span class='where'>where S::Owned: <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a></span>",];implementors["gazetta_core"] = ["impl&lt;'a,&nbsp;G&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Deref.html' title='core::ops::Deref'>Deref</a> for <a class='struct' href='gazetta_core/view/struct.Site.html' title='gazetta_core::view::Site'>Site</a>&lt;'a,&nbsp;G&gt; <span class='where'>where G: <a class='trait' href='gazetta_core/render/trait.Gazetta.html' title='gazetta_core::render::Gazetta'>Gazetta</a> + 'a, G::SiteMeta: 'a</span>","impl&lt;'a,&nbsp;G&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Deref.html' title='core::ops::Deref'>Deref</a> for <a class='struct' href='gazetta_core/view/struct.Page.html' title='gazetta_core::view::Page'>Page</a>&lt;'a,&nbsp;G&gt; <span class='where'>where G: <a class='trait' href='gazetta_core/render/trait.Gazetta.html' title='gazetta_core::render::Gazetta'>Gazetta</a> + 'a, G::PageMeta: 'a, G::SiteMeta: 'a</span>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
