[package]
name = "gazetta-render-ext"
version = "0.1.0"
authors = ["Steven Allen <steven@stebalien.com>"]

[dependencies.gazetta-core]
path = "../core"

[dependencies]
horrorshow = "0.5"
pulldown-cmark = "0.0.3"
