(function() {var implementors = {};
implementors["ansi_term"] = [{text:"impl&lt;'a, S:&nbsp;'a + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/alloc/borrow/trait.ToOwned.html\" title=\"trait alloc::borrow::ToOwned\">ToOwned</a> + ?<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"ansi_term/struct.ANSIGenericString.html\" title=\"struct ansi_term::ANSIGenericString\">ANSIGenericString</a>&lt;'a, S&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;&lt;S as <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/alloc/borrow/trait.ToOwned.html\" title=\"trait alloc::borrow::ToOwned\">ToOwned</a>&gt;::<a class=\"type\" href=\"https://doc.rust-lang.org/nightly/alloc/borrow/trait.ToOwned.html#associatedtype.Owned\" title=\"type alloc::borrow::ToOwned::Owned\">Owned</a>: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a>,&nbsp;</span>",synthetic:false,types:["ansi_term::display::ANSIGenericString"]},];
implementors["chrono"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"chrono/naive/struct.TsSeconds.html\" title=\"struct chrono::naive::TsSeconds\">TsSeconds</a>",synthetic:false,types:["chrono::naive::datetime::TsSeconds"]},];
implementors["gazetta_core"] = [{text:"impl&lt;'a, G&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"gazetta_core/view/struct.Site.html\" title=\"struct gazetta_core::view::Site\">Site</a>&lt;'a, G&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;G: <a class=\"trait\" href=\"gazetta_core/render/trait.Gazetta.html\" title=\"trait gazetta_core::render::Gazetta\">Gazetta</a> + 'a,<br>&nbsp;&nbsp;&nbsp;&nbsp;G::<a class=\"type\" href=\"gazetta_core/render/trait.Gazetta.html#associatedtype.SiteMeta\" title=\"type gazetta_core::render::Gazetta::SiteMeta\">SiteMeta</a>: 'a,&nbsp;</span>",synthetic:false,types:["gazetta_core::view::site::Site"]},{text:"impl&lt;'a, G&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"gazetta_core/view/struct.Page.html\" title=\"struct gazetta_core::view::Page\">Page</a>&lt;'a, G&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;G: <a class=\"trait\" href=\"gazetta_core/render/trait.Gazetta.html\" title=\"trait gazetta_core::render::Gazetta\">Gazetta</a> + 'a,<br>&nbsp;&nbsp;&nbsp;&nbsp;G::<a class=\"type\" href=\"gazetta_core/render/trait.Gazetta.html#associatedtype.PageMeta\" title=\"type gazetta_core::render::Gazetta::PageMeta\">PageMeta</a>: 'a,<br>&nbsp;&nbsp;&nbsp;&nbsp;G::<a class=\"type\" href=\"gazetta_core/render/trait.Gazetta.html#associatedtype.SiteMeta\" title=\"type gazetta_core::render::Gazetta::SiteMeta\">SiteMeta</a>: 'a,&nbsp;</span>",synthetic:false,types:["gazetta_core::view::page::Page"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
